module.exports = {
    FIREBASE_API_KEY: '',
    FIREBASE_AUTH_DOMAIN: '',
    FIREBASE_DATABASE: '',
    FIREBASE_STORAGE: '',
    FIREBASE_MESSAGING_SENDER: '',
    ITSC_AUTH_URL: '',
    ITSC_SERVICE_URL: '',
    CDN_URL: ''
}
