
//
// How to parse parameters from URL string
// Reference: http://stackoverflow.com/questions/11582512/how-to-get-url-parameters-with-javascript/11582513#11582513
// Usage:
//   var myvar = getURLParameter('myvar');
//

// function getURLParameter(name) {
//   return decodeURIComponent((new RegExp('[?|&]' + name + '=' + '([^&;]+?)(&|#|;|$)').exec(location.search) || [null, ''])[1].replace(/\+/g, '%20')) || null;
// }


// Returns a random integer between min (included) and max (included)
// Using Math.round() will give you a non-uniform distribution!
// Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random
function getRandomIntInclusive(min, max) {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

//
// This function is automatically generated by the Firebase web console
// Please change this function accordingly
// Reference: https://console.firebase.google.com
//

function initalizeFirebase() {

  // Initialize Firebase
  var config = {
    apiKey: "AIzaSyCI2oKMFJECxHD11aRCxzVNG5M-Uvm8X20",
    authDomain: "teamform-ad42e.firebaseapp.com",
    databaseURL: "https://teamform-ad42e.firebaseio.com",
    storageBucket: "teamform-ad42e.appspot.com",
    messagingSenderId: "609768855060"
  };
  firebase.initializeApp(config);

}

//
// User-defined function - Useful for retrieving an object once, without 3-way sync
// For 3-way sync, use $firebaseObject or $firebaseArray provided by AngularFire
//

// function retrieveOnceFirebase(firebase, refPath, callbackFunc) {
// 	firebase.database().ref(refPath).once("value").then(callbackFunc);
// }

function gotoURL(path, params, $window) {
  var urlParams = "";
  if (params !== undefined && params.length !== 0) urlParams += "?";
  for ( i = 0; i < params.length; i++ ) {
    if (i !== 0) urlParams += "&";
    urlParams += params[i].key + "=" + params[i].value;
  }

  var absPath = "http://" + $window.location.host + path + urlParams;
  $window.location.href = absPath;
}

function checkLogin($cookies) {
  username = $cookies.get("username",{path:"/"});
  if (username !== undefined) return true;
  else return false;
}
